version: '3.5'
services:
  php83:
    container_name: "php83"
    image: php83:latest #for locally usage
#    image: ityannred/php83:latest
    ports:
      - "8032:80"
    volumes:
      - /home/yann/docker/dirmap/sources/XXXX:/home/web
    #restart: always