version: '3.5'
services:
  php83vialtic:
    container_name: "php83vialtic"
    image: ityannred/php83:latest #php83
    ports:
      - "8033:80"
    volumes:
      - /home/yann/sources/vialtic:/home/web
    networks:
      - vialtic
    labels:
      - "traefik.http.routers.php83vialtic.rule=host(`vialtic.localhost`)"
      - "traefik.http.routers.php83vialtic.service=php83vialtic"
      - "traefik.http.services.php83vialtic.loadbalancer.server.port=80"
    #restart: always

  mysql57vialtic:
    container_name: "mysql57vialtic"
    image: mysql:5.7.41
    volumes:
      - /home/yann/docker/dirmap/mysql57vialtic-data:/var/lib/mysql
      #- /home/yann/docker/dirmap/mysql57vialtic-conf/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3333:3306"
    restart: always
    command: --sql_mode= #-max_allowed_packet=32505856
    networks:
      - vialtic
    environment:
      - MYSQL_ROOT_PASSWORD=vialtic96
      - TZ=Europe/Paris
    #restart: always

  traefik:
    container_name: "traefik"
    # The official v2 Traefik docker image
    image: traefik:v2.2
    networks:
      - vialtic
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker=true
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    restart: always
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  vialtic:
    name: vialtic
    driver: bridge